[package]
name = "trainermon_rs_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
mongodb = "2"
rust-argon2 = "2.0.0"
serde = "1.0.193"
